#服务配置
server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: ${project} #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: ${driver}
    url: ${url}
    username: ${userName}
    password: ${password}
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update